"""category_name_column_added

Revision ID: 4de3fea25f08
Revises: 84c99c1853a5
Create Date: 2025-04-23 18:35:09.473138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4de3fea25f08'
down_revision: Union[str, None] = '84c99c1853a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sqla_catgory', sa.Column('name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'sqla_catgory', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sqla_catgory', type_='unique')
    op.drop_column('sqla_catgory', 'name')
    # ### end Alembic commands ###
